In [1]:
import numpy as np
import pandas as pd

## DataTypes and Attribute

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],
              [4,5,6.1]])

a3 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.1]])

In [6]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

## Generate a 2x3 array with random values between 0 and 1

In [9]:
np.random.rand(2, 3)

array([[0.16678705, 0.72386381, 0.25890455],
       [0.85424048, 0.15728708, 0.35476211]])

## Generate a 2x3 array with random integers between 10 and 50

In [11]:
np.random.randint(10, 50, size=(3, 3))

array([[40, 42, 21],
       [37, 46, 25],
       [39, 23, 21]])

## Generate a 2x3 array with random values from a normal distribution

In [13]:
np.random.randn(2, 3)

array([[ 0.01280489,  0.61993518,  0.26851296],
       [-1.06512147,  2.07770934,  1.0434441 ]])

## Generate a 2x3 array with random choices from the list [1, 2, 3, 4, 5]

In [15]:
np.random.choice([1, 2, 3, 4, 5], size=(2, 3))

array([[5, 3, 3],
       [5, 2, 2]])

## 1.Manuplating & Comparing Array

### Arithmatic

In [18]:
a1

array([1, 2, 3])

In [19]:
once = np.ones(3)

In [20]:
a1 + once

array([2., 3., 4.])

In [21]:
a1 - once

array([0., 1., 2.])

In [22]:
a1 * once

array([1., 2., 3.])

In [23]:
a2 * a2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 37.21]])

In [24]:
a2/a1

array([[1.        , 1.        , 1.        ],
       [4.        , 2.5       , 2.03333333]])

In [25]:
a2 % a1

array([[0. , 0. , 0. ],
       [0. , 1. , 0.1]])

## Random seed 
keep the random value sm ever time on run

In [27]:
np.random.seed(0)
np.random.random((2,3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

## Aggregation

In [29]:
sam_list = [1,2,3,4]
sam_list

[1, 2, 3, 4]

In [30]:
type(sam_list)

list

In [31]:
sum(sam_list)

10

## Creating Large Array

In [33]:
large_array = np.random.random(10000)

In [34]:
large_array

array([0.43758721, 0.891773  , 0.96366276, ..., 0.03760018, 0.01178774,
       0.99626787])

In [35]:
%timeit sum(large_array) #Python sum function
%timeit np.sum(large_array) #numpy np.sum functtion

866 μs ± 21.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
7.88 μs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## dot product

In [37]:
np.random.seed(0)
item = np.random.randint(20, size=(5,3))

In [38]:
item

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [39]:
price = np.array([8,12,15])

In [40]:
price

array([ 8, 12, 15])

In [41]:
item_df = pd.DataFrame(item, index = ["Mon","Tue","Wed","Thue","Fri"],
            columns = ["Almond","Penut","Cashew"])

In [42]:
item_df

Almond  Penut  Cashew
Mon       12     15       0
Tue        3      3       7
Wed        9     19      18
Thue       4      6      12
Fri        1      6       7

In [43]:
item.dot(price)

array([276, 165, 570, 284, 185])

In [44]:
item_df["Total ($)"] = item.dot(price)

In [45]:
item_df

Almond  Penut  Cashew  Total ($)
Mon       12     15       0        276
Tue        3      3       7        165
Wed        9     19      18        570
Thue       4      6      12        284
Fri        1      6       7        185

## Sorting in Numpy

In [99]:
sort_ex = np.random.randint(20,size=(3,3))

In [101]:
sort_ex

array([[19, 14,  7],
       [ 0,  1,  9],
       [ 0, 10,  3]])

In [103]:
np.sort(sort_ex)

array([[ 7, 14, 19],
       [ 0,  1,  9],
       [ 0,  3, 10]])

In [105]:
np.argsort(sort_ex)

array([[2, 1, 0],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [107]:
a1

array([1, 2, 3])

In [109]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [117]:
np.argmin(a1) #returns index of min value

0

In [115]:
np.argmax(a1) #returns index of man value

2

## Practical Example - Numpy in Action!!!

<img src="numpy-images/panda.png" height="100" >

In [127]:
from matplotlib.image import imread

In [129]:
panda = imread("numpy-images/panda.png")

In [132]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [134]:
panda.size,panda.shape

(24465000, (2330, 3500, 3))

## Car 
<img src="numpy-images/car-photo.png" >

In [144]:
car = imread("numpy-images/car-photo.png")

In [146]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

## Dog
<img src="numpy-images/dog-photo.png">

In [151]:
dog = imread("numpy-images/dog-photo.png")

In [153]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274